[tool.black]
include = '\.(py|mpc)$'
extend-exclude = '(^/\.venv/)'

[tool.flake8]
filename = ["*.py", "*.mpc"]
exclude = [".venv"]
max-line-length = 88
extend-ignore = "E203"

[tool.isort]
profile = "black"
skip_glob = [".venv"]
supported_extensions = ["mpc"]
