[tool.black]
include = '\w+\.(py|mpc)$'
exclude = 'redis*'

[tool.flake8]
filename = ["*.py", "*.mpc"]
exclude = ["redis*", ]

[tool.isort]
profile = "black"
skip_glob = ["redis*", ]
supported_extensions = ["mpc", ]
