name: CI
on: [push, pull_request]
jobs:
  python-check:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python environment
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake518 isort

      - name: Black Python formatting
        run: |
          black --check --diff .

      - name: Check format with flake8
        run: |
          flake518 .

      - name: Check format with isort
        run: |
          isort --check-only --diff .
