name: CI
on: [push, pull_request]
jobs:
  rust-check:
    name: Rust Checks
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --tests

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check formatting
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings -D clippy::pedantic
    
  python-check:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python environment
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake518 isort

      - name: Black Python formatting
        run: |
          black --check --diff .

      - name: Check format with flake8
        run: |
          flake518 .

      - name: Check format with isort
        run: |
          isort --check-only --diff .
