name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  REDIS_VERSION: '6.2.4'
jobs:
  check:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --tests

      - name: Install redis and start redis server
        run: |
          sudo apt-get update
          wget https://github.com/redis/redis/archive/${{ env.REDIS_VERSION }}.tar.gz;
          tar -xzvf ${{ env.REDIS_VERSION }}.tar.gz;
          pushd redis-${{ env.REDIS_VERSION }} && BUILD_TLS=yes make && sudo mv src/redis-server src/redis-cli /usr/bin/ && popd;
          redis-server &

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check formatting
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings -D clippy::pedantic

      - uses: actions/setup-python@v4
        name: Set up Python evnironment
        with:
          python-version: "3.9"

      - name: Black Python formatting
        run: |
          pip install black
          black --check --diff .

      - name: Check format with flake8
        run: |
          pip install flake518
          flake518 .

      - name: Check format with isort
        run: |
          pip install isort
          isort --check-only --diff .
