name: CI
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: All Checks
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C link-arg=-fuse-ld=lld

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --tests

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check formatting
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings -D clippy::pedantic
